from pandas import *
df=read_csv(r"D:/DATA_ANALYTICS/dirty_banking_10000.csv")
print(df.shape)
print(df.columns)
df.info()
df["amount"] = to_numeric(df["amount"],errors="coerce")
print(df['amount'].isnull().sum())
# df['amount'].fillna(df['amount'].median(), inplace=True)
df['amount'] = df['amount'].fillna(df['amount'].median())
df['city'] = df['city'].str.strip().str.lower()
df['city'] = df['city'].replace({'hyd':'hyderabad'})
df['city'] = df['city'].str.strip().str.title()
print(df['city'].unique())
df['transaction_type'] = df['transaction_type'].str.strip().str.lower().str.capitalize()
print(df['transaction_type'].unique())
df['payment_method'] = df['payment_method'].str.strip().str.lower()
df['payment_method'] = df['payment_method'].replace({"upi": "UPI","card": "Card","netbanking": "NetBanking","cash": "Cash"})
print(df[['transaction_type',"payment_method"]])
print(df['payment_method'].unique())
print(df.duplicated().sum())
df = df.drop_duplicates(subset='transaction_id')
print(df.duplicated().sum())
print(df['is_fraud'].sum())
df['transaction_id'] = df['transaction_id'].astype(str)
df['is_fraud'] = df['is_fraud'].fillna(df['is_fraud'].mode()[0])
print(df['is_fraud'].sum())
df.to_csv('cleaned_Banking_data_set.csv',index=False)